version: '3.7'

services:
  # FastAPI instance 1 connected to db_1
  app_instance_1:
    build: task_manager
    container_name: app_instance_1
    environment:
      - DB_HOST=db_1
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8001:8001"
    depends_on:
      - db_1

  # FastAPI instance 2 connected to db_2
  app_instance_2:
    build: task_manager
    container_name: app_instance_2
    environment:
      - DB_HOST=db_2
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8002:8001"
    depends_on:
      - db_2

  # PostgreSQL instance 1 (db_1) for replication
  db_1:
    image: postgres:latest
    container_name: db_1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_1_data:/var/lib/postgresql/data
      - ./postgresql/db_1/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql/db_1/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  # PostgreSQL instance 2 (db_2) for replication
  db_2:
    image: postgres:latest
    container_name: db_2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_2_data:/var/lib/postgresql/data
      - ./postgresql/db_2/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql/db_2/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  db_1_data:
  db_2_data: